---
permalink: install-linux/qsg-linux.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Linux QSG, RHEL QSG, quick installation 
summary: Linux平台上的Unified Manager快速入門指南。 
---
= Linux安裝的快速入門指示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以下載安裝套件、並在實體或虛擬Red Hat Enterprise Linux或CentOS平台上安裝Unified Manager。



== 系統需求

* 作業系統： Red Hat Enterprise Linux 7.x 版和 8.0 版至 8.9 版、或 CentOS 7.x 版（以 x86_64 架構為基礎）、安裝時使用 OS 安裝程式 * Software Selection* 選項的「 Server with GUI 」基礎環境
* RAM：12 GB、CPU：總共9572 MHz
* 可用磁碟空間：目錄中有 100 GB 磁碟空間 `/opt/netapp/data`，根分割區中有 50 GB 。對於個別安裝的 `/opt`和 `/var/log`目錄，請確保 `/opt`有 15 GB ， 16 GB ， `/var/log`以及 `/tmp` 10 GB 的可用空間。


如需詳細的系統需求，以及在安全站台中安裝產品的相關資訊，請參閱link:../install-linux/concept_requirements_for_install_unified_manager.html["安裝Unified Manager的需求"]和link:http://mysupport.netapp.com/matrix["互通性對照表"]。



== 安裝Active IQ Unified Manager



=== 下載安裝程式

. 下載 `ActiveIQUnifiedManager-<version>.zip`安裝軟件包及代碼簽名證書(`.sig`）(`.pem`和數字簽名）。
. 在您下載安裝檔案的目錄中、執行：
+
`# unzip ActiveIQUnifiedManager-<version>.zip`





=== 驗證完整性

執行下列命令來驗證安裝程式套件的完整性：

* 執行 `openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>`以使用程式碼簽署憑證中的公開金鑰建立檔案。
* 執行 `openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip`以驗證安裝程式套件上的簽章。




=== 驗證儲存庫組態

設定Red Hat Enterprise Linux或CentOS儲存庫的程序是站台專屬的。您可以使用 `pre_install_check.sh`安裝套件中的指令碼來驗證作業系統的組態。如果您的系統已連線至網際網路、您會自動收到設定Red Hat Enterprise Linux或CentOS儲存庫的指示。

`# sudo ./pre_install_check.sh`



=== 安裝Unified Manager

Unified Manager 會使用 `yum`公用程式來安裝軟體和任何相關軟體。由於Red Hat Enterprise Linux或CentOS的映像各不相同、因此安裝的套件取決於映像中的軟體。公用程式會 `yum`決定要安裝的相關軟體套件。如果您需要有關相關軟體套件的詳細資訊，請參閱link:../install-linux/reference_red_hat_and_centos_software_and_installation_requirements.html["Linux軟體與安裝需求"]。

若要安裝 Unified Manager ，請從安裝檔案解壓縮的目錄中，以 root 使用者或使用執行下列命令 `sudo`：

`# yum install netapp-um<version>.x86_64.rpm`

或

`% sudo yum install netapp-um<version>.x86_64.rpm`

安裝結束時、會顯示連線至Unified Manager Web UI的資訊。如果您無法連線至 Web UI ，請參閱 `README`軟體隨附的檔案，以取得連接埠 443 限制的詳細資訊。
